res18_pre: '/mnt/sdb/wyn/model/resnet18.pth'
img_train: '/mnt/sdb/wyn/data/PIAD/Unseen_obj/Img_train.txt'
img_val: '/mnt/sdb/wyn/data/PIAD/Unseen_obj/Img_test.txt'
img_test: '/mnt/sdb/wyn/data/PIAD/Unseen_obj/Img_test.txt'
point_train: '/mnt/sdb/wyn/data/PIAD/Unseen_obj/Point_train.txt'
point_val: '/mnt/sdb/wyn/data/PIAD/Unseen_obj/Point_test.txt'
point_test: '/mnt/sdb/wyn/data/PIAD/Unseen_obj/Point_test.txt'
batch_size: 16
lr: 0.0001
Epoch: 50
Setting: 'Unseen_obj'
num_heads: 4
emb_dim: 512
proj_dim: 512
N_p: 64
N_raw: 2048
num_affordance: 24
pairing_num: 2
run_type: 'train'

human_dictionary_train: '/mnt/sdb/wyn/data/PIAD/Unseen_obj/hk_train.txt'
human_dictionary_val: '/mnt/sdb/wyn/data/PIAD/Unseen_obj/hk_test.txt'
human_dictionary_test: '/mnt/sdb/wyn/data/PIAD/Unseen_obj/hk_test.txt'

object_dictionary_train: '/mnt/sdb/wyn/data/PIAD/Unseen_obj/ok_train.txt'
object_dictionary_val: '/mnt/sdb/wyn/data/PIAD/Unseen_obj/ok_test.txt'
object_dictionary_test: '/mnt/sdb/wyn/data/PIAD/Unseen_obj/ok_test.txt'